name: kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
           
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Navigate to Terraform directory
      run: cd env/prod

    - name: Terraform Init
      run: terraform init 

    - name: Navigate to Terraform directory
      run: cd env/prod

    - name: Terraform Validate
      run: terraform validate

    - name: Navigate to Terraform directory
      run: cd env/prod

    - name: PWD
      run: pwd

    - name: Terraform Apply
      run: terraform apply -auto-approve 
    
    - name: Navigate to Terraform directory
      run: cd env/prod
      
    - run: echo "$(terraform output -raw LBHostname)"
      id: LBHostname
