name: kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
           
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3
 
    - name: Terraform Init
      run: terraform -chdir=env/prod init 

    - name: Terraform Validate
      run: terraform -chdir=env/prod validate

    - name: LS
      run: ls

    - name: Terraform Apply
      run: terraform -chdir=env/prod apply -auto-approve 
  
    - run: echo "$(terraform -chdir=env/prod output -raw LBHostname)"
      id: LBHostname
